# Generated by Django 4.2.11 on 2024-03-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_enquiry_table_dropdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry_table',
            name='dropdown',
            field=models.CharField(max_length=100),
        ),
    ]
